image: jps12/workshop-ci-entrega-02_frontend
image: jps12/workshop-ci-entrega-02_backend

docker:
  script:
    - docker push jps12/workshop-ci-entrega-02_backend
    - docker push jps12/workshop-ci-entrega-02_backend
  only:
    - main

frontend:
  script:
    - echo "Hi o front está funcionando"
  only: 
    - main

backend:
  script:
    - echo "Hi o backend está funcionando"
  only: 
    - main