stages:
  - build

variables:
  FRONTEND_IMAGE: $DOCKER_USER/workshop-ci-entrega-02_frontend

build frontend:
  image: docker:latest
  stage: build
  context: ./frontend
  services:
    - docker:dind
  before_script:
    - cd frontend
  script: 
    - docker build -f Dockerfile -t $FRONTEND_IMAGE:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $FRONTEND_IMAGE:latest